apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-project-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ayubfarahh/EKS-Project.git
    targetRevision: main
    path: kubernetes/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true