apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048
  namespace: default
spec:
  replicas: 2
  selector: { matchLabels: { app: game-2048 } }
  template:
    metadata: { labels: { app: game-2048 } }
    spec:
      containers:
      - name: web
        image: 940622738555.dkr.ecr.eu-west-2.amazonaws.com/2048:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: game-2048
  namespace: default
spec:
  selector: { app: game-2048 }
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-2048
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: lab.ayubs.uk
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - lab.ayubs.uk
    secretName: game-2048-tls
  rules:
  - host: lab.ayubs.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: game-2048
            port:
              number: 80

