name: Terraform Apply

on:
  workflow_dispatch:  

env:
  AWS_REGION: eu-west-2
  TF_VERSION: 1.9.0

jobs:
  apply-infra:
    name: Apply Infrastructure (VPC, IAM, EKS)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init (Infra)
      working-directory: terraform/infra
      run: terraform init

    - name: Terraform Apply (Infra)
      working-directory: terraform/infra
      run: terraform apply -auto-approve

  apply-helm:
    name: Apply Helm Charts + IRSA
    runs-on: ubuntu-latest
    needs: apply-infra

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init (Helm)
      working-directory: terraform/helm
      run: terraform init

    - name: Terraform Apply (Helm)
      working-directory: terraform/helm
      run: terraform apply -auto-approve
