name: Terraform Destroy 

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2
  TF_VERSION: 1.9.0

jobs:
  destroy:
    name: Destroy Terraform Stack
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Destroy Helm Charts
      working-directory: terraform
      run: terraform destroy -auto-approve -target=module.helm

    - name: Destroy IRSA Roles
      working-directory: terraform
      run: terraform destroy -auto-approve -target=module.irsa

    - name: Destroy EKS Cluster
      working-directory: terraform
      run: terraform destroy -auto-approve -target=module.eks

    - name: Destroy IAM
      working-directory: terraform
      run: terraform destroy -auto-approve -target=module.iam

    - name: Destroy Networking
      working-directory: terraform
      run: terraform destroy -auto-approve -target=module.networking
