name: Terraform Plan

on:
  push:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-plan.yml"

env:
  TF_WORKING_DIR: terraform
  AWS_REGION: eu-west-2
  TF_VERSION: 1.6.6

jobs:
  validate-plan:
    name: Validate and Plan 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Format Check
      run: terraform fmt -check -recursive
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Run TFLint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: v0.50.3

    - name: TFLint Scan
      run: tflint --recursive
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with: 
        directory: terraforn
        framework: terraform

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Terraform Plan
      run: terraform plan
      working-directory: ${{ env.TF_WORKING_DIR }}
